version: '3.9'

services:
  mysql:
    container_name: votehub-mysql
    image: mysql:8.0.32
    restart: always
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=state_register
    volumes:
      - ./data/sql-init/state-register-init.sql:/docker-entrypoint-initdb.d/state-register-init.sql
      - ./data/sql-init/polling-station-init.sql:/docker-entrypoint-initdb.d/polling-station-init.sql
    ports:
      - "3308:3306"
